# config/packages/vich_uploader.yaml or app/config/config.yml
vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        user:
            uri_prefix: /images/users
            upload_destination: '%kernel.project_dir%/public/images/users'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        components:
            uri_prefix: /images/components
            upload_destination: '%kernel.project_dir%/public/images/components'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer